import Icons from "../elements/Icons";

const Appsettings = {
    api : {
        audio : "/wp-json/wp/v2/media/?media_type=audio",
        base : 'https://weisgerber.fmgrafikdesign.de/wp-json/better-rest-endpoints/v1',
        count_parameter: 'per_page',
        domain: "https://weisgerber.fmgrafikdesign.de",
        image_archive: "/page/37/",
        library: "",
        order : "ASC",
        orderby : "menu_order",
        pois_to_retrieve: '100',
        privacy_page: "/page/3/",
        publication: "/page/65/",
        interviews: "/page/93/",
        imprint: "/page/167/",
        stelen : "/stele/",
        texte : "/texte/"
    },
    map : {
        // tslint:disable-next-line:max-line-length
        accessToken : 'pk.eyJ1IjoiZm1ncmFmaWtkZXNpZ24iLCJhIjoiY2p0YWJyeHdiMDk4ZjQ0bnVsNmxxOTVxNiJ9.VT7_EBjMcWpDWzXyxyPuuw',
        center: [7.1122986, 49.279558],
        maxZoom: 22,
        minZoom: 5,
        provider : 'mapbox',
        style: 'mapbox://styles/mapbox/streets-v11',
        zoom: 13
    },
    menu : {
        items: [
            {
                icon: Icons.home,
                name: 'Start',
                route: '/start'
            },
            {
                icon: Icons.map,
                name: 'Karte',
                route: '/karte'
            },
            {
                icon: Icons.location,
                name: 'Stelen',
                route: '/stelen'
            },
            {
                icon: Icons.book,
                name: 'Bibliothek',
                route: '/bibliothek'
            },
            {
                icon: Icons.bullhorn,
                name: 'Aktuell',
                route: '/aktuell'
            }
        ]
    },
    offer_directions : false,
    poi_route: '/stelen/',
    text_route: '/bibliothek/texte/',
    title : 'Albert Weisgerber'

};

const books = "<!-- Generated by IcoMoon.io -->\n" +
    "<svg version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" width=\"36\" height=\"32\" viewBox=\"0 0 36 32\">\n" +
    "<title>books</title>\n" +
    "<path d=\"M7 4h-6c-0.55 0-1 0.45-1 1v22c0 0.55 0.45 1 1 1h6c0.55 0 1-0.45 1-1v-22c0-0.55-0.45-1-1-1zM6 10h-4v-2h4v2z\"></path>\n" +
    "<path d=\"M17 4h-6c-0.55 0-1 0.45-1 1v22c0 0.55 0.45 1 1 1h6c0.55 0 1-0.45 1-1v-22c0-0.55-0.45-1-1-1zM16 10h-4v-2h4v2z\"></path>\n" +
    "<path d=\"M23.909 5.546l-5.358 2.7c-0.491 0.247-0.691 0.852-0.443 1.343l8.999 17.861c0.247 0.491 0.852 0.691 1.343 0.443l5.358-2.7c0.491-0.247 0.691-0.852 0.443-1.343l-8.999-17.861c-0.247-0.491-0.852-0.691-1.343-0.443z\"></path>\n" +
    "</svg>\n";

export default Appsettings;